- id: sync-uv-pre-commit
  name: Sync uv and pre commit
  description: Sync uv and pre commit
  language: python
  language_version: "3.12"
  entry: "sync_uv_pre_commit"
  minimum_pre_commit_version: "2.9.2"
  require_serial: true
  always_run: true
