- id: sync-uv-pre-commit
  name: Sync uv and pre commit
  description: Sync uv and pre commit
  language: script
  entry: "uv run script.py"
  minimum_pre_commit_version: "3.5.0"
  require_serial: true
  always_run: true