name: lint

on:
  push:
    branches: [dev]
    paths:
      - "**.py"
      - ".github/workflows/lint.yaml"
      - "pyproject.toml"
      - "ruff.toml"
      - "pyrightconfig.json"
      - ".pre-commit-config.yaml"
  pull_request:
    branches: [dev, main]
    paths:
      - "**.py"
      - ".github/workflows/lint.yaml"
      - "pyproject.toml"
      - "ruff.toml"
      - "pyrightconfig.json"
      - ".pre-commit-config.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v4
        id: install-python
        with:
          python-version: 3.9

      - name: Install uv
        uses: yezz123/setup-uv@v4
        id: install-uv

      - name: Install dependencies
        run: |
          uv sync

      - name: Code checks
        run: |
          uv run pre-commit run --all-files --show-diff-on-failure